name: Deploy Production Dependencies and Code 🚀
on:
  workflow_dispatch:
  push:
    branches:
      - 'releases/v*'
    tags-ignore:
      - '*.*'

jobs:
  build:
    name: Build Production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - uses: actions/setup-node@v7.0.0
        with:
          node-version-file: '.node-version'

      - name: Clobber lib
        run: rm -rf lib

      - name: Set up .gitignore
        run: |
          sed -i -e's/^lib/# lib/' -e's/^node_module/# node_modules/' .gitignore

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Install Production node_modules
        run: |
          npm ci --omit=dev

      - name: Commit and Push
        # Keep the run green if the commit fails for the lack of changes
        continue-on-error: True
        run: |
          git config user.email "${{ secrets.GIT_CONFIG_EMAIL }}"
          git config user.name "${{ secrets.GIT_CONFIG_NAME }}"
          git add .
          git commit -m "Deploy Production Code for Commit ${{ github.sha }} 🚀"
          git push

  validate:
    name: Validate Release Candidate 🧪
    needs: build
    secrets: inherit
    uses: ./.github/workflows/integration.yml
    with:
      action-ref: ${{ github.ref_name }}
